# 3251 Group 2 Final Project: Insurance Claims

**Members: Mo Attia, Uri Barak, Jason Goodfield, Zain Syed, Pauline Vincent**

In [2]:
import numpy as np
import math
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
import statsmodels.formula.api as sm
from statsmodels.tools import add_constant as add_constant

plt.rcParams['figure.figsize'] = (40.0, 20.0)
%matplotlib inline

In [29]:
#Read dataset
names = ['customer', 'state', 'cust_lifetime_value', 'response', 'coverage_type', 'education', 'effective_to_date', 'employment_status', 'gender', 'income' , 'location_code', 'marital_status', 'monthly_premium', 'months_since_last_claim', 'months_since_policy_start', 'open_complaints', 'num_policies', 'policy_type', 'policy', 'renew_offer_type', 'sales_channel', 'total_claim_amount', 'vehicle_class', 'vehicle_size']

file = 'AutoInsurance.csv'
#'https://raw.githubusercontent.com/jgoodz8/3251_Project_Group2/master/AutoInsurance.csv' I don't think can link with private repository

df = pd.read_csv(file, header = 0, names = names)

df.head()

,customer,state,cust_lifetime_value,response,coverage_type,education,effective_to_date,employment_status,gender,income,...,months_since_policy_start,open_complaints,num_policies,policy_type,policy,renew_offer_type,sales_channel,total_claim_amount,vehicle_class,vehicle_size
0,BU79786,Washington,2763.519279,No,Basic,Bachelor,2/24/2011,Employed,F,56274,...,5,0,1,Corporate Auto,Corporate L3,Offer1,Agent,384.811147,Two-Door Car,Medsize
1,QZ44356,Arizona,6979.535903,No,Extended,Bachelor,1/31/2011,Unemployed,F,0,...,42,0,8,Personal Auto,Personal L3,Offer3,Agent,1131.464935,Four-Door Car,Medsize
2,AI49188,Nevada,12887.431650,No,Premium,Bachelor,2/19/2011,Employed,F,48767,...,38,0,2,Personal Auto,Personal L3,Offer1,Agent,566.472247,Two-Door Car,Medsize
3,WW63253,California,7645.861827,No,Basic,Bachelor,1/20/2011,Unemployed,M,0,...,65,0,7,Corporate Auto,Corporate L2,Offer1,Call Center,529.881344,SUV,Medsize
4,HB64268,Washington,2813.692575,No,Basic,Bachelor,3/2/2011,Employed,M,43836,...,44,0,1,Personal Auto,Personal L1,Offer1,Agent,138.130879,Four-Door Car,Medsize